apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/home-operations/kopiur
          ref: 0.9.2
          skipInitSubmodules: true
        includePaths:
          - deploy/crds/*.yaml
