---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        githubRelease:
          slug: rajsinghtech/garage-operator
          tag: v0.7.3
          assetNames:
            - install.yaml
          disableAutoChecksumValidation: true
