---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        githubRelease:
          slug: aclerici38/pocket-id-operator
          tag: v0.12.0
          assetNames:
            - install.yaml
          disableAutoChecksumValidation: true
