---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/budimanjojo/talhelper
          ref: v3.1.16
          skipInitSubmodules: true
        includePaths:
          - pkg/config/schemas/talconfig.json
